# Generated by Django 4.1 on 2023-05-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Viewer_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mercury", models.BooleanField(blank=True, verbose_name="Mercury")),
                ("venus", models.BooleanField(blank=True, verbose_name="Venus")),
                ("earth", models.BooleanField(blank=True, verbose_name="Earth")),
                ("mars", models.BooleanField(blank=True, verbose_name="Mars")),
                ("jupiter", models.BooleanField(blank=True, verbose_name="Jupiter")),
                ("saturn", models.BooleanField(blank=True, verbose_name="Saturn")),
                ("uranus", models.BooleanField(blank=True, verbose_name="Uranus")),
                ("neptune", models.BooleanField(blank=True, verbose_name="Neptune")),
                ("pluto", models.BooleanField(blank=True, verbose_name="Pluto")),
                (
                    "compute_3D",
                    models.BooleanField(blank=True, verbose_name="Compute in 3D"),
                ),
            ],
        ),
    ]
